version: '3'

# This docker compose file is only for demonstrative purposes, not for an actual prod deployment
# secrets in this file are therefore not sensitive

services:
  collab.io-db-dev:
    image: mysql:8.0.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: collabio
    volumes:
      - collabio-data-dev:/var/lib/mysql

volumes:
  collabio-data-dev: